[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
talent_olympics_nft_mint_vault_swap = "2K2jn1PU9TjxmL3PkmRRCMs1pvaqZEbGjSyHbpqdRLdT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[[test.genesis]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
program = "tests/mpl_core.so"

# [test.validator]
# bind_address = "0.0.0.0"
# url = "https://api.mainnet-beta.solana.com"
# ledger = ".anchor/test-ledger"
# rpc_port = 8899

# [[test.validator.clone]]
# address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
