[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
talent_olympics_nft_mint_vault_swap = "2K2jn1PU9TjxmL3PkmRRCMs1pvaqZEbGjSyHbpqdRLdT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
